[package]
name = "folioharbor-worker"
edition.workspace = true
publish.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
folioharbor-application = { path = "../../crates/application", version = "0.1.0" }
folioharbor-domain = { path = "../../crates/domain", version = "0.1.0" }
folioharbor-epub = { path = "../../crates/epub", version = "0.1.0" }
folioharbor-http = { path = "../../crates/http", version = "0.1.0" }
folioharbor-postgres = { path = "../../crates/postgres", version = "0.1.0" }
folioharbor-storage-local = { path = "../../crates/storage-local", version = "0.1.0" }
lettre.workspace = true
opentelemetry.workspace = true
opentelemetry_sdk.workspace = true
base64.workspace = true
secrecy.workspace = true
thiserror.workspace = true
tokio.workspace = true
time.workspace = true
tracing.workspace = true
tracing-opentelemetry.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true
zeroize.workspace = true

[lints]
workspace = true

[dev-dependencies]
folioharbor-test-support = { path = "../../crates/test-support", version = "0.1.0" }
opentelemetry_sdk = { workspace = true, features = ["testing"] }
sha2.workspace = true
serde_json.workspace = true
sqlx.workspace = true
tempfile = "3.20"
zip.workspace = true
