/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["verifyEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["forgotPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["currentSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listSessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/sessions/{session_id}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["revokeSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/libraries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listLibraries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/libraries/{library_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getLibrary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/libraries/{library_id}/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateLibrarySettings"];
        trace?: never;
    };
    "/api/v1/libraries/{library_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listLibraryMembers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/libraries/{library_id}/members/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["removeLibraryMember"];
        options?: never;
        head?: never;
        patch: operations["changeLibraryMemberRole"];
        trace?: never;
    };
    "/api/v1/libraries/{library_id}/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["inviteLibraryMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invitations/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Atomically accepts an email-bound invitation and returns only a masked email hint on account mismatch. */
        post: operations["acceptLibraryInvitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/libraries/{library_id}/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Reserves library quota atomically before any EPUB content is accepted. Requires holding.edit. */
        post: operations["createUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/libraries/{library_id}/uploads/{upload_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Returns only uploads in the requested library; readers without holding.edit cannot inspect upload status. */
        get: operations["getUploadStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/libraries/{library_id}/uploads/{upload_id}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** @description Streams EPUB bytes into the existing reservation. Interrupted or oversized attempts become failed and can retry this same upload_id safely. */
        put: operations["receiveUploadContent"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/libraries/{library_id}/books": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Lists active Holdings visible in this Library with stable keyset pagination. The cursor is opaque and clients must not parse or construct it. */
        get: operations["listLibraryBooks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/libraries/{library_id}/items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Returns a transport-safe projection only after resolving the Item through a visible active Holding. */
        get: operations["getLibraryItem"];
        put?: never;
        post?: never;
        /** @description Immediately revokes Item access and starts a seven-day recovery window. Logical quota is retained until the recovery window closes. */
        delete: operations["deleteLibraryItem"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/libraries/{library_id}/items/{item_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Restores a deleted Item strictly before its seven-day recovery window ends. */
        post: operations["restoreLibraryItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/items/{item_id}/manifest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Returns a Readium-style online-reading projection after a fresh item.read authorization check. Opaque resource links use same-origin HTTP paths and never expose archive paths. */
        get: operations["getPublicationManifest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/items/{item_id}/resources/{resource_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Reauthorizes item.read on every request, including transformed-cache hits, then returns one sanitized allowed EPUB resource. Sanitized local references resolve to this same-origin route with opaque IDs. */
        get: operations["getPublicationResource"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/items/{item_id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Streams the immutable original EPUB after an independent item.download authorization check. A reader is allowed only when the owning Library explicitly enables reader downloads. */
        get: operations["downloadOriginalPublication"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        /** @description Returns the same authorization, validator, range, length, media-type, and disposition headers as GET without reading Blob content. */
        head: operations["headOriginalPublication"];
        patch?: never;
        trace?: never;
    };
    "/api/v1/manifestations/{manifestation_id}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Returns the authenticated user's retained progress only while this Manifestation is readable through an active Holding and Item. */
        get: operations["getReadingProgress"];
        /** @description Atomically records one idempotent device mutation. Matching base versions advance global state; stale bases update only device state and return both positions. */
        put: operations["updateReadingProgress"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterRequest: {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
        };
        VerifyEmailRequest: {
            token: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
        };
        ForgotPasswordRequest: {
            /** Format: email */
            email: string;
        };
        ResetPasswordRequest: {
            token: string;
            /** Format: password */
            new_password: string;
        };
        AcceptedResponse: {
            /** @enum {string} */
            status: "pending" | "accepted";
        };
        SessionIssuedResponse: {
            /** Format: uuid */
            user_id: string;
            /** Format: uuid */
            session_id: string;
        };
        Session: {
            /** Format: uuid */
            user_id: string;
            /** Format: uuid */
            session_id: string;
            is_current: boolean;
            /** @enum {string} */
            status: "active" | "idle_expired" | "absolute_expired" | "revoked";
        };
        LibraryCapabilities: {
            /** @description Effective holding.edit capability */
            can_upload: boolean;
            /** @description Effective member.invite capability */
            can_invite_members: boolean;
            /** @description Effective library.manage capability for role and removal operations */
            can_manage_members: boolean;
            /** @description Effective library.manage capability for settings */
            can_manage_settings: boolean;
        };
        Library: {
            /** Format: uuid */
            library_id: string;
            name: string;
            /** @enum {string} */
            role: "owner" | "editor" | "reader";
            reader_download_enabled: boolean;
            capabilities: components["schemas"]["LibraryCapabilities"];
        };
        LibraryMember: {
            /** Format: uuid */
            user_id: string;
            /** @enum {string} */
            role: "owner" | "editor" | "reader";
        };
        InvitationAcceptance: {
            /** @enum {string} */
            status: "accepted" | "wrong_account" | "unverified" | "expired" | "consumed" | "invalid";
            /**
             * Format: uuid
             * @description Present only when accepted
             */
            library_id?: string | null;
            /** @description Masked and present only for wrong_account */
            email_hint?: string | null;
        };
        CreateUploadRequest: {
            file_name: string;
            /** @enum {string} */
            media_type: "application/epub+zip" | "application/octet-stream";
            declared_bytes: number;
        };
        UploadStatus: {
            /** Format: uuid */
            upload_id: string;
            /** Format: uuid */
            library_id: string;
            file_name: string;
            /** @enum {string} */
            media_type: "application/epub+zip" | "application/octet-stream";
            declared_bytes: number;
            received_bytes: number;
            /** @enum {string} */
            state: "created" | "receiving" | "received" | "queued" | "validating" | "importing" | "ready" | "duplicate" | "failed" | "expired" | "retry_wait";
            status_url: string;
            /** @description Stable safe code; implementation or storage details are never exposed */
            error_code?: string | null;
            /**
             * Format: uuid
             * @description Existing or newly created visible Item for Ready and Duplicate completion
             */
            item_id?: string | null;
        };
        BookSummary: {
            /** Format: uuid */
            item_id: string;
            primary_title: string;
            authors: string[];
            languages: string[];
            /** @enum {string} */
            media_type: "application/epub+zip" | "application/octet-stream";
            /** @description Effective online-reading capability */
            can_read: boolean;
            /** @description Effective original-file download capability; independent from can_read */
            can_download: boolean;
        };
        BookPage: {
            items: components["schemas"]["BookSummary"][];
            /** @description Opaque cursor; absent or null at the end */
            next_cursor?: string | null;
        };
        ItemDetail: {
            /** Format: uuid */
            item_id: string;
            /** Format: uuid */
            manifestation_id: string;
            primary_title: string;
            authors: string[];
            languages: string[];
            identifiers: string[];
            /** @enum {string} */
            media_type: "application/epub+zip" | "application/octet-stream";
            /** @description Effective online-reading capability */
            can_read: boolean;
            /** @description Effective original-file download capability; independent from can_read */
            can_download: boolean;
        };
        PublicationManifest: {
            metadata: {
                title: string;
                authors: string[];
                languages: string[];
            };
            /**
             * Format: uuid
             * @description Exact Manifestation identifier used by reading-state synchronization
             */
            manifestationId: string;
            readingOrder: components["schemas"]["PublicationLink"][];
            resources: components["schemas"]["PublicationLink"][];
            toc: components["schemas"]["PublicationLink"][];
            links: components["schemas"]["PublicationLink"][];
        };
        PublicationLink: {
            /** @description Same-origin API link containing only an opaque resource identifier */
            href: string;
            type: string;
            rel?: string;
            title?: string;
        };
        Locator: {
            href: string;
            type?: string;
            locations: {
                progression?: number;
                position?: number;
                totalProgression?: number;
                fragments?: string[];
            };
            text?: {
                before?: string;
                highlight?: string;
                after?: string;
            };
            extensions: {
                /** @constant */
                version: 1;
                values: {
                    [key: string]: boolean | number | string;
                };
            };
        };
        ReadingProgress: {
            /** Format: uuid */
            manifestationId: string;
            /** Format: uuid */
            packageId?: string | null;
            /** Format: uuid */
            contentUnitId?: string | null;
            locator: components["schemas"]["Locator"];
            version: number;
            /** Format: date-time */
            updatedAt: string;
        };
        DeviceReadingProgress: {
            /** Format: uuid */
            deviceId: string;
            locator: components["schemas"]["Locator"];
            /** Format: date-time */
            updatedAt: string;
        };
        ConflictGlobalReadingProgress: {
            /** Format: uuid */
            manifestationId: string;
            /** Format: uuid */
            packageId?: string | null;
            /** Format: uuid */
            contentUnitId?: string | null;
            locator: components["schemas"]["Locator"] | null;
            version: number;
            /** Format: date-time */
            updatedAt: string | null;
        };
        UpdateReadingProgressRequest: {
            /**
             * Format: uuid
             * @description Stable authenticated user identifier; the server rejects the mutation if it differs from the current session actor
             */
            accountId: string;
            /** Format: uuid */
            deviceId: string;
            /** Format: uuid */
            clientMutationId: string;
            baseVersion: number;
            /** Format: uuid */
            packageId?: string | null;
            /** Format: uuid */
            contentUnitId?: string | null;
            locator: components["schemas"]["Locator"];
        };
        ProgressConflictProblem: components["schemas"]["ProblemDetails"] & {
            global: components["schemas"]["ConflictGlobalReadingProgress"];
            device: components["schemas"]["DeviceReadingProgress"];
        };
        ProblemDetails: {
            /** Format: uri */
            type: string;
            title: string;
            status: number;
            detail: string;
            instance: string;
            /**
             * @example malformed_json
             * @example invalid_json_body
             * @example unsupported_media_type
             * @example invalid_session_id
             * @example unauthenticated
             * @example csrf_failed
             * @example rate_limited
             * @example session_not_found
             */
            code: string;
            /** @description ULID request identifier */
            request_id: string;
            /** @description Stable field/code pairs for invalid requests; display text remains client-localized */
            fields?: components["schemas"]["ProblemFieldViolation"][];
        };
        ProblemFieldViolation: {
            field: string;
            code: string;
        };
    };
    responses: {
        /** @description Authorized original EPUB bytes or headers */
        OriginalEpub: {
            headers: {
                "Accept-Ranges"?: "bytes";
                "Content-Length"?: number;
                /** @description Present for partial responses */
                "Content-Range"?: string;
                /** @description Safe quoted ASCII fallback plus RFC 5987 UTF-8 filename */
                "Content-Disposition"?: string;
                /** @description Strong opaque immutable Blob validator; never the raw content hash */
                ETag?: string;
                "X-Content-Type-Options"?: "nosniff";
                [name: string]: unknown;
            };
            content: {
                "application/epub+zip": string;
            };
        };
        /** @description RFC 9457 problem details */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://library.example/problems/invalid-json-body",
                 *       "title": "Invalid request body",
                 *       "status": 422,
                 *       "detail": "The request body could not be accepted as JSON for this operation.",
                 *       "instance": "/problems/01JREQ00000000000000000000",
                 *       "code": "invalid_json_body",
                 *       "request_id": "01JREQ00000000000000000000"
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description RFC 9457 stale-base conflict containing the current global (version 0 with a null locator when absent) and reporting-device positions, or a safe problem without positions when a mutation id is reused for a different command */
        ProgressConflict: {
            headers: {
                /** @example private, no-store */
                "Cache-Control"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProgressConflictProblem"] | components["schemas"]["ProblemDetails"];
            };
        };
        /** @description The per-user 30-day mutation retention capacity is full; retry after the oldest retained mutation expires */
        ProgressMutationCapacity: {
            headers: {
                /** @description Seconds until the oldest retained mutation expires */
                "Retry-After"?: number;
                /** @example private, no-store */
                "Cache-Control"?: string;
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://library.example/problems/rate-limited",
                 *       "title": "Too many requests",
                 *       "status": 429,
                 *       "detail": "Too many requests have been made.",
                 *       "instance": "/problems/01JREQ00000000000000000000",
                 *       "code": "rate_limited",
                 *       "request_id": "01JREQ00000000000000000000"
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description A malformed UUID was supplied for the session_id path parameter; the use case is not invoked */
        InvalidSessionIdProblem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://library.example/problems/invalid-session-id",
                 *       "title": "Invalid path parameter",
                 *       "status": 400,
                 *       "detail": "The session_id path parameter must be a UUID.",
                 *       "instance": "/problems/01JREQ00000000000000000000",
                 *       "code": "invalid_session_id",
                 *       "request_id": "01JREQ00000000000000000000"
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description A malformed UUID was supplied for a catalog path parameter; the use case is not invoked */
        InvalidIdentifierProblem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://library.example/problems/invalid-identifier",
                 *       "title": "Invalid path parameter",
                 *       "status": 400,
                 *       "detail": "The catalog path parameter must be a UUID.",
                 *       "instance": "/problems/01JREQ00000000000000000000",
                 *       "code": "invalid_identifier",
                 *       "request_id": "01JREQ00000000000000000000"
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Registration accepted without account enumeration */
        RegistrationAccepted: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "status": "pending"
                 *     }
                 */
                "application/json": components["schemas"]["AcceptedResponse"];
            };
        };
        /** @description Password reset accepted whether or not the account exists */
        PasswordResetAccepted: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "status": "accepted"
                 *     }
                 */
                "application/json": components["schemas"]["AcceptedResponse"];
            };
        };
        /** @description Fresh opaque session and CSRF cookies issued; secrets are absent from JSON */
        SessionIssued: {
            headers: {
                /** @example folioharbor_session=opaque; HttpOnly; Secure; SameSite=Lax; Path=/ */
                "Set-Cookie"?: string;
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "user_id": "018f47b5-58b4-7ba6-9a3a-d9f41f17a26d",
                 *       "session_id": "018f47b5-58b4-7ba6-9a3a-d9f41f17a26e"
                 *     }
                 */
                "application/json": components["schemas"]["SessionIssuedResponse"];
            };
        };
        /** @description Current safe session metadata */
        CurrentSession: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "user_id": "018f47b5-58b4-7ba6-9a3a-d9f41f17a26d",
                 *       "session_id": "018f47b5-58b4-7ba6-9a3a-d9f41f17a26e",
                 *       "is_current": true,
                 *       "status": "active"
                 *     }
                 */
                "application/json": components["schemas"]["Session"];
            };
        };
        /** @description Safe metadata for sessions owned by the authenticated user */
        SessionList: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example [
                 *       {
                 *         "user_id": "018f47b5-58b4-7ba6-9a3a-d9f41f17a26d",
                 *         "session_id": "018f47b5-58b4-7ba6-9a3a-d9f41f17a26e",
                 *         "is_current": true,
                 *         "status": "active"
                 *       }
                 *     ]
                 */
                "application/json": components["schemas"]["Session"][];
            };
        };
        /** @description Upload accepted; poll the Location status resource. Retrying content after failed/interrupted receipt reuses the same upload_id. */
        UploadAccepted: {
            headers: {
                /** @description Upload status resource */
                Location: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["UploadStatus"];
            };
        };
    };
    parameters: {
        /**
         * @description Opaque session-bound CSRF token for unsafe authenticated requests
         * @example opaque-csrf-token
         */
        CsrfToken: string;
        LibraryId: string;
        UserId: string;
        UploadId: string;
        ItemId: string;
        ManifestationId: string;
    };
    requestBodies: {
        Register: {
            content: {
                /**
                 * @example {
                 *       "email": "reader@example.com",
                 *       "password": "correct horse battery staple"
                 *     }
                 */
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        VerifyEmail: {
            content: {
                /**
                 * @example {
                 *       "token": "opaque-email-verification-token"
                 *     }
                 */
                "application/json": components["schemas"]["VerifyEmailRequest"];
            };
        };
        Login: {
            content: {
                /**
                 * @example {
                 *       "email": "reader@example.com",
                 *       "password": "correct horse battery staple"
                 *     }
                 */
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        ForgotPassword: {
            content: {
                /**
                 * @example {
                 *       "email": "reader@example.com"
                 *     }
                 */
                "application/json": components["schemas"]["ForgotPasswordRequest"];
            };
        };
        ResetPassword: {
            content: {
                /**
                 * @example {
                 *       "token": "opaque-password-reset-token",
                 *       "new_password": "a new correct horse battery staple"
                 *     }
                 */
                "application/json": components["schemas"]["ResetPasswordRequest"];
            };
        };
        CreateUpload: {
            content: {
                /**
                 * @example {
                 *       "file_name": "book.epub",
                 *       "media_type": "application/epub+zip",
                 *       "declared_bytes": 1048576
                 *     }
                 */
                "application/json": components["schemas"]["CreateUploadRequest"];
            };
        };
        UpdateReadingProgress: {
            content: {
                "application/json": components["schemas"]["UpdateReadingProgressRequest"];
            };
        };
    };
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["Register"];
        responses: {
            202: components["responses"]["RegistrationAccepted"];
            400: components["responses"]["Problem"];
            413: components["responses"]["Problem"];
            415: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
        };
    };
    verifyEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["VerifyEmail"];
        responses: {
            /** @description Email address verified */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Problem"];
            413: components["responses"]["Problem"];
            415: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["Login"];
        responses: {
            200: components["responses"]["SessionIssued"];
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            413: components["responses"]["Problem"];
            415: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Opaque session-bound CSRF token for unsafe authenticated requests
                 * @example opaque-csrf-token
                 */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session revoked and authentication cookies cleared */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
        };
    };
    forgotPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["ForgotPassword"];
        responses: {
            202: components["responses"]["PasswordResetAccepted"];
            400: components["responses"]["Problem"];
            413: components["responses"]["Problem"];
            415: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
        };
    };
    resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["ResetPassword"];
        responses: {
            200: components["responses"]["SessionIssued"];
            400: components["responses"]["Problem"];
            413: components["responses"]["Problem"];
            415: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
        };
    };
    currentSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["CurrentSession"];
            401: components["responses"]["Problem"];
        };
    };
    listSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["SessionList"];
            401: components["responses"]["Problem"];
        };
    };
    revokeSession: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Opaque session-bound CSRF token for unsafe authenticated requests
                 * @example opaque-csrf-token
                 */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                /** @example 018f47b5-58b4-7ba6-9a3a-d9f41f17a26d */
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Owned session revoked; current-session cookies are cleared */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["InvalidSessionIdProblem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    listLibraries: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Libraries visible to the authenticated member with server-derived capabilities */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Library"][];
                };
            };
            401: components["responses"]["Problem"];
        };
    };
    getLibrary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                library_id: components["parameters"]["LibraryId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Authorized library detail with server-derived capabilities */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Library"];
                };
            };
            400: components["responses"]["InvalidSessionIdProblem"];
            401: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    updateLibrarySettings: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Opaque session-bound CSRF token for unsafe authenticated requests
                 * @example opaque-csrf-token
                 */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                library_id: components["parameters"]["LibraryId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    /** @description Owner-controlled reader original-download toggle; does not alter item.read */
                    reader_download_enabled?: boolean;
                };
            };
        };
        responses: {
            /** @description Settings updated and audited atomically */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["InvalidSessionIdProblem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    listLibraryMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                library_id: components["parameters"]["LibraryId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Library members visible to the authenticated member */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryMember"][];
                };
            };
            400: components["responses"]["InvalidSessionIdProblem"];
            401: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    removeLibraryMember: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Opaque session-bound CSRF token for unsafe authenticated requests
                 * @example opaque-csrf-token
                 */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                library_id: components["parameters"]["LibraryId"];
                user_id: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Member removed and audited atomically */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["InvalidSessionIdProblem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    changeLibraryMemberRole: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Opaque session-bound CSRF token for unsafe authenticated requests
                 * @example opaque-csrf-token
                 */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                library_id: components["parameters"]["LibraryId"];
                user_id: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    role: "owner" | "editor" | "reader";
                };
            };
        };
        responses: {
            /** @description Role changed and audited atomically */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["InvalidSessionIdProblem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    inviteLibraryMember: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Opaque session-bound CSRF token for unsafe authenticated requests
                 * @example opaque-csrf-token
                 */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                library_id: components["parameters"]["LibraryId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    /** @enum {string} */
                    role: "editor" | "reader";
                };
            };
        };
        responses: {
            /** @description Invitation created and audited atomically */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["InvalidSessionIdProblem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            /** @description Invitation delivery is unavailable; no invitation or allowed audit is persisted */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "https://library.example/problems/mail-delivery-unavailable",
                     *       "title": "Dependency unavailable",
                     *       "status": 503,
                     *       "detail": "A required service is temporarily unavailable.",
                     *       "instance": "/problems/01JREQ00000000000000000000",
                     *       "code": "mail_delivery_unavailable",
                     *       "request_id": "01JREQ00000000000000000000"
                     *     }
                     */
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    acceptLibraryInvitation: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Opaque session-bound CSRF token for unsafe authenticated requests
                 * @example opaque-csrf-token
                 */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    token: string;
                };
            };
        };
        responses: {
            /** @description Safe invitation acceptance state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitationAcceptance"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            413: components["responses"]["Problem"];
            415: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    createUpload: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Opaque session-bound CSRF token for unsafe authenticated requests
                 * @example opaque-csrf-token
                 */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                library_id: components["parameters"]["LibraryId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["CreateUpload"];
        responses: {
            202: components["responses"]["UploadAccepted"];
            400: components["responses"]["InvalidSessionIdProblem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            /** @description Declared upload size exceeds 1 GiB */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            422: components["responses"]["Problem"];
            507: components["responses"]["Problem"];
        };
    };
    getUploadStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                library_id: components["parameters"]["LibraryId"];
                upload_id: components["parameters"]["UploadId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current durable upload state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadStatus"];
                };
            };
            400: components["responses"]["InvalidSessionIdProblem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    receiveUploadContent: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Opaque session-bound CSRF token for unsafe authenticated requests
                 * @example opaque-csrf-token
                 */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                library_id: components["parameters"]["LibraryId"];
                upload_id: components["parameters"]["UploadId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/epub+zip": string;
                "application/octet-stream": string;
            };
        };
        responses: {
            202: components["responses"]["UploadAccepted"];
            400: components["responses"]["InvalidSessionIdProblem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            /** @description Upload is not in a receipt or retryable state */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            413: components["responses"]["Problem"];
            415: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            507: components["responses"]["Problem"];
        };
    };
    listLibraryBooks: {
        parameters: {
            query?: {
                /** @description Opaque keyset cursor returned by the previous page */
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path: {
                library_id: components["parameters"]["LibraryId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One display-ready row per visible library Holding */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookPage"];
                };
            };
            400: components["responses"]["InvalidIdentifierProblem"];
            401: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    getLibraryItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                library_id: components["parameters"]["LibraryId"];
                item_id: components["parameters"]["ItemId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Authorized item detail without Blob, Package, storage, parser, or audit internals */
            200: {
                headers: {
                    /** @description Weak validator covering item and capability inputs */
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemDetail"];
                };
            };
            400: components["responses"]["InvalidIdentifierProblem"];
            401: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    deleteLibraryItem: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Opaque session-bound CSRF token for unsafe authenticated requests
                 * @example opaque-csrf-token
                 */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                library_id: components["parameters"]["LibraryId"];
                item_id: components["parameters"]["ItemId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Item is deleted or was already deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["InvalidIdentifierProblem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    restoreLibraryItem: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Opaque session-bound CSRF token for unsafe authenticated requests
                 * @example opaque-csrf-token
                 */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                library_id: components["parameters"]["LibraryId"];
                item_id: components["parameters"]["ItemId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Item is active or was already active */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["InvalidIdentifierProblem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            /** @description The seven-day recovery window elapsed */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            503: components["responses"]["Problem"];
        };
    };
    getPublicationManifest: {
        parameters: {
            query?: never;
            header?: {
                /** @description Accepts strong or weak matching validators and the wildcard `*` */
                "If-None-Match"?: string;
            };
            path: {
                item_id: components["parameters"]["ItemId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Authorized publication manifest */
            200: {
                headers: {
                    /** @description Strong package and parser-version validator */
                    ETag?: string;
                    /** @example private, no-cache */
                    "Cache-Control"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicationManifest"];
                };
            };
            /** @description Package validator matched */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["InvalidIdentifierProblem"];
            401: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    getPublicationResource: {
        parameters: {
            query?: never;
            header?: {
                /** @description Accepts strong or weak matching validators and the wildcard `*` */
                "If-None-Match"?: string;
            };
            path: {
                item_id: components["parameters"]["ItemId"];
                /** @description Opaque package-scoped resource identifier */
                resource_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sanitized document, stylesheet, image, or font with restrictive browser-isolation headers */
            200: {
                headers: {
                    /** @description Strong Item */
                    ETag?: string;
                    /** @example default-src 'none'; img-src 'self' data: blob:; style-src 'self' 'unsafe-inline'; font-src 'self' data: blob:; script-src 'none'; form-action 'none'; frame-src 'none'; frame-ancestors 'self' */
                    "Content-Security-Policy"?: string;
                    /** @example nosniff */
                    "X-Content-Type-Options"?: string;
                    /** @example no-referrer */
                    "Referrer-Policy"?: string;
                    /** @example private, no-cache */
                    "Cache-Control"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/xhtml+xml": string;
                    "text/html": string;
                    "text/css": string;
                    "image/png": string;
                    "image/jpeg": string;
                    "image/gif": string;
                    "image/webp": string;
                    "font/woff": string;
                    "font/woff2": string;
                };
            };
            /** @description Resource validator matched after fresh authorization */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["InvalidIdentifierProblem"];
            401: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    downloadOriginalPublication: {
        parameters: {
            query?: never;
            header?: {
                /** @description At most one byte range field-line */
                Range?: string;
                /** @description Uses weak comparison; supports wildcard and comma-list members across repeated field-lines */
                "If-None-Match"?: string;
            };
            path: {
                item_id: components["parameters"]["ItemId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["OriginalEpub"];
            206: components["responses"]["OriginalEpub"];
            /** @description Immutable Blob validator matched after fresh authorization */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["InvalidIdentifierProblem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            /** @description Multiple */
            416: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            503: components["responses"]["Problem"];
        };
    };
    headOriginalPublication: {
        parameters: {
            query?: never;
            header?: {
                /** @description At most one byte range field-line */
                Range?: string;
                /** @description Uses weak comparison; supports wildcard and comma-list members across repeated field-lines */
                "If-None-Match"?: string;
            };
            path: {
                item_id: components["parameters"]["ItemId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["OriginalEpub"];
            206: components["responses"]["OriginalEpub"];
            /** @description Immutable Blob validator matched after fresh authorization */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["InvalidIdentifierProblem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            /** @description Multiple */
            416: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            503: components["responses"]["Problem"];
        };
    };
    getReadingProgress: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                manifestation_id: components["parameters"]["ManifestationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current global reading position */
            200: {
                headers: {
                    /** @example "progress-v3" */
                    ETag?: string;
                    /** @example private, no-store */
                    "Cache-Control"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadingProgress"];
                };
            };
            /** @description No saved progress exists */
            204: {
                headers: {
                    /** @example "progress-v0" */
                    ETag?: string;
                    /** @example private, no-store */
                    "Cache-Control"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["InvalidIdentifierProblem"];
            401: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    updateReadingProgress: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Opaque session-bound CSRF token for unsafe authenticated requests
                 * @example opaque-csrf-token
                 */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
                /** @description Must encode the same version as JSON baseVersion */
                "If-Match": string;
            };
            path: {
                manifestation_id: components["parameters"]["ManifestationId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["UpdateReadingProgress"];
        responses: {
            /** @description Global progress advanced */
            200: {
                headers: {
                    /** @example "progress-v4" */
                    ETag?: string;
                    /** @example private, no-store */
                    "Cache-Control"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadingProgress"];
                };
            };
            400: components["responses"]["InvalidIdentifierProblem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["ProgressConflict"];
            413: components["responses"]["Problem"];
            415: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            429: components["responses"]["ProgressMutationCapacity"];
            503: components["responses"]["Problem"];
        };
    };
}
